branch-defaults:
  ci/eb-deploy:
    environment: Nestjs-CD-EB-env
environment-defaults:
  Nestjs-CD-EB-env:
    branch: null
    repository: null
global:
  application_name: Nest.js-CD-EB
  default_ec2_keyname: hub-key
  default_platform: Node.js 18 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
