version: 2.1
orbs:
  eb: circleci/aws-elastic-beanstalk@2.0.1
commands:
  build-commands:
    description: Install Packages, Build project, generate .ci.env
    steps:
      - run: npm install
      - run: npm run build
      - run: echo "DATABASE_URL=$DATABASE_URL" >> .ci.env
      - run: ls
      - run: pwd
  unit-test-commands:
    description: Unit Test for project
    steps:
      - run: npm install -g dotenv-cli
      - run: npm run ci:unit
  e2e-test-commands:
    description: e2e Test for project
    steps:
      - run: npm install -g dotenv-cli
      - run: npm run ci:e2e

jobs:
  build-phase:
    machine: true
    resource_class: aws-self-runner/hoplin
    steps:
      - checkout
      - build-commands
      - persist_to_workspace:
          root: .
          paths:
            - .
  unit-test:
    docker:
      - image: cimg/node:18.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - unit-test-commands
  e2e-test:
    docker:
      - image: cimg/node:18.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - e2e-test-commands
  elastic-beanstalk-deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - eb/setup
      - run:
          command: eb deploy Nestjs-CD-Pipeline-env

workflows:
  build_test_deploy:
    jobs:
      - build-phase
      # - unit-test:
      #     requires:
      #       - build-phase
      # - e2e-test:
      #     requires:
      #       - build-phase
      # - elastic-beanstalk-deploy:
      #     requires:
      #       - unit-test
      #       - e2e-test
